runserver:
	python -m manage runserver

install:
	pip install -r requirements.txt

startapp:
	cd apps && django-admin startapp $(app)

makemigrations:
	python -m manage makemigrations

migrate:
	python -m manage migrate

createsuperuser:
	python -m manage createsuperuser