# Generated by Django 5.0.1 on 2024-01-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'waiting'), (2, 'accepted')], default=1),
        ),
    ]
