# Generated by Django 5.0.1 on 2024-01-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'pending'), (2, 'accepted')], default=1),
        ),
    ]
